### PR TITLE
Module Version Bump and Fixes

### PR DESCRIPTION
**Pull request by XxInvictus**
- amberelectric module version bump to 2.0.12 (previous was very out-of-date)
- Fixes and syntax updates with new version

### CODE REVIEW

**Comment by mo5h** [comment]
Tested their change and looks like it works (on latest home assistant core 2024.12.1), or at least the custom component's loading as expected, changes look reasonable. One consideration I can think of is that this change may result in this component not working with older versions of home assistant, looks like the amberelectric module update is a breaking change.

**Comment by XxInvictus** [comment]
I can't say I have done extensive backwards-compat testing but given no changes were made to Home Assistant functions this is very unlikely to break previous HA versions. Any breaking changes in the downstream Amber Electric module are not breaking changes for HA.

**Comment by mo5h** [comment]
I think it may conflict with the Amber Electric official integration
(Bundled in HA core), because that integration had a dependency on the
older version of the Amber electric library, and the new version of the
library isn't backwards compatible.
I noticed when testing the inverted case (i.e with the version without your
changes installed, which with the latest HA core resulted either the
official integration, or this integration failing depending on which one
"won" the dependency conflict)


It looks like there's a field in the `manifest.json` to specify what
version of home assistant it's compatible with, and it looks the official
integration in core was released in version 2024.12.1 (
https://github.com/home-assistant/core/commit/621c66a2147ee4fff784ee75767fa784681aca76),
so we'd just need to update that ` "homeassistant": "2024.11.2",` in
`hacs.json` to `2024.12.1`

**Comment by XxInvictus** [comment]
I am torn on this, I have updated the file anyway but in terms of compatibility I also want to remain cognizant that there is nothing preventing this from being compatible with prior HA versions if that integration isn't in use. Incompatible with an integration is different to incompatible with HA itself. I have still updated the version because without a full-time maintainer and while it is an unofficial port I am sure the owner of this repo and the people here don't want to get inundated with the flood of people having cross-integration compatibility/race-condition issues :D

**Comment by XxInvictus** [comment]
@mo5h did you have any follow on issues? I am seeing some weird behaviour and the integration is stuck, won't start on boot, reload won't kick it off :/ I have been screwing around with it all night trying to reduce changes to even more minimal than the `with` refactoring but nothing, just pain...

**Comment by mo5h** [comment]
Yeah, it looks like they've changed the maximum amount of days they let you poll down to 7 days, so I had to update it to only query 7 days back, I've been a bit lazy and just updating the code directly on my instance, so I don't have a patch, but to fix it I updated the  `_get_usages` function in `coordinator.py` to look like:

```
    def _get_usages(self) -> list[Usage]:
        today = dt_util.now().date()
        return self._api.get_usage(
            self.site_id, start_date=(today - timedelta(weeks=1)), end_date=today
        )
```

I also updated `_async_update_data` function just re-throw the exception instead of whatever it was doing before, because that made it a _lot_ easier to debug

I _did_ notice that yesterday's data hasn't come through yet for me, but it looks like it's also not showing up in their official webapp, so that indicates to me that  it's not a problem with this component

**Comment by XxInvictus** [comment]
After all that I am going to close this off as the original creator appears to have fixed it all in their repo 👍😆 
Ref: https://github.com/Tmbao/amberelectric-usages/pull/12

**Pull request closed without merging**
